### ISSUE TITLE
No included license?

### ISSUE THREAD

**Issue by MyroG** [pool-parlor/pool-parlor-table#2]
In which license is this project shared right now?

Based on [this link](https://choosealicense.com/no-permission/), a project that doesn't include a license is technically not open source. Some clarifications could be interesting.

**Comment by ToastersPlease** [comment]
In discussions with Metaphira on which license to use.

**Comment by ToastersPlease** [comment]
https://github.com/pool-parlor/pool-parlor-table/blob/master/Assets/metaphira/Modules/BilliardsModule/LICENSE
